import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./header/NavBar";
import { Inter } from "next/font/google";
import { HeaderAnnouncement } from "./header/HeaderAnnouncement";
import { HowItWorks } from "./howItWorks/howItWorks";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});





export const metadata: Metadata = {
  title: "Hirian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div className="flex flex-col">

         <HeaderAnnouncement />
          <NavBar />

          <main className="flex flex-col">
            {/* container adiciona larguras responsivas automaticas. */}
            <div>
              {children} 
            </div>

            
            
          </main>


    
          <footer>

          </footer>

        </div>
        
        </body>
    </html>
  );
}
